name: Go Tests

on:
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: Run Tests
      run: make test
